version: '3'
services:
  top.api:
    image: docker.pkg.github.com/darktimeoff/nestjs-top-api/top-api:develop
    container_name: top-api
    restart: always
    ports: 
      - 3000:300
    volumes:
      - ./.env:/opt/app/.env
