name: Publish Docker
on: 
  push: 
    branches: [master]
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/Darktimeoff/Nestjs-Top-Api/top-api
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tags: "develop"